### ISSUE TITLE
Checkpoint 2 Ready for Review

### ISSUE THREAD

**Issue by Carlos-Leon98** [Carlos-Leon98/Inventory-Management-System#3]
Good evening @pawaitemadisoncollege,

The second review is ready to be reviewed.

1. Database Design and creation 

This is a high-level diagram I created not for the project but for myself to guide myself when creating the database.

- CA: Categories
- P: Products
- L: Locations
- S: Sections
- OD: Order Details
- O: Orders
- CU: Customers
- U: Users
- P: Passwords

![image](https://github.com/Carlos-Leon98/Inventory-Management-System/assets/69998153/f24d33d3-f056-4b11-83d0-c283952dfc95)

2. DAO class were created.
3. Unit Test for one of the DAO is ready (The other ones are planned for this week's goals).

Unit test passed,

![image](https://github.com/Carlos-Leon98/Inventory-Management-System/assets/69998153/c619afb1-cace-453d-b6f9-098c5add59c0)

The exception was for the insertSuccess method. The Category was created and inserted correctly into the database but the test failed because of the set of products related to the category record. (null record vs empty record). This failure is expected, but still working on how to manage the data that is entered as the set of products.

![image](https://github.com/Carlos-Leon98/Inventory-Management-System/assets/69998153/6f42f8eb-d839-4880-85ce-39f9559e3c08)
![image](https://github.com/Carlos-Leon98/Inventory-Management-System/assets/69998153/6536b3a3-3b95-46ef-92db-a96e7b5bfcec)

Please, let me know about any feedback,

Thank you,
Carlos Leon Rivas.

**Comment by pawaitemadisoncollege** [comment]
Hi @Carlos-Leon98!

- [ ] Can you please add a screenshot of your Database ERD - you can generate this right in IntelliJ from the database view.

**Comment by Carlos-Leon98** [comment]
Hi @pawaitemadisoncollege,

Thank you for your feedback. Here I left my responses point by point.

I will take this spring break week to work on the missed requirements not only for this checkpoint but also for the previous checkpoint. In the meantime, I can provide you the screenshot of my database ERD and one of the points for which I have a question.

- [X] Add a screenshot of your Database ERD so that I can review and provide feedback - you can generate this right in IntelliJ from the database view.

Response - Please let me know if this is ok or if you prefer me to place the ERD on my repository.

![inventory_system_manager_ERD](https://github.com/Carlos-Leon98/Inventory-Management-System/assets/69998153/29a70354-a64d-4145-8999-dca99db58a84)


- [ ] Time Log needs updating. Remember this should include all time spent working on Ent Java - the weekly work and project work.

Response - Still need to get used to this, but I added the time that I worked on the checkpoint 2 requirements, would you want me to add more accurate times?


Thank you,
Carlos Leon Rivas.

**Comment by pawaitemadisoncollege** [comment]
Hi @Carlos-Leon98 - you've been working hard on this and it shows! 

- [ ] Great job implementing the generic dao. However, you still need tests for each entity with the generic dao though so that you can verify all generic dao methods work with every entity and all relationships. You currently have a test for Category with the GenericDao, I would call this CategoryDaoTest. Create a similar test for each entity.  Be sure to test the relationships too. For example, if I delete a product or order, verify that what should happen to any related records does happen.
