### ISSUE TITLE
Peer Review

### ISSUE THREAD

**Issue by jhaefner97** [Carlos-Leon98/Inventory-Management-System#5]
Hi Carlos, 

First off, I owe you an apology for giving you this feedback in written form so late, it was a disservice to you. I hope the conversations we had helped a bit, but my feedback from the notes I took are as follows - 

# Design/Code Review 1

### Reviewer: Josh Haefner

|Item |Considerations| Comments/Suggestions|
|--------|---------|---|
|||Reviewer comments and suggestions go here. Each item should have *at least* one "kudos" and two suggestions for improvement|
|**Problem Statement**|1. Accurately describes project purpose<br> 2. Is professional and free of typos, slang, etc.<br> 3. Fully explains the problem and the solution<br> 4. Is understandable by the average person| Carlos's problem statement accurately describes what the applications intended use case is for, and I think he did a great job creating a digestible scope for MVP1. However, I am not too familiar with the intricacies of inventory management, and think that some of the industry lingo was hard to understand.|
|**Design Documentation**|1. Navigation/flow through the application is logical and easy to use. <br>2. The order in which values are displayed are logical and easy to understand/use <br>3. The order in which the form fields entered are logical and easy to understand/use<br>4. All data discussed/documented (problem statement, flow, db design, etc.) is represented on the screens |The flow through the application makes sense and is logical.  Carlos described the user flow through the wireframes and felt very intuitive and easy to follow. I would say that some of the pages felt a bit "busy" to me, but I will attribute that to a lack of knowledge within the industry. |
|**Data model/Database**|1. Everything on the screens and problem statement/flow is represented in the model <br> 2. There is at least one 1-to-many relationship.<br> 3. The model represents good database design <br>|The wireframes are well laid out, and properly represents the problem statements, furthermore, the database was probably the strongest component of the project so far. The tables have relationships, and are logically sound. I have no recommendations for improvement within this space. |
|**Code**|1. Proper Maven project structure is used<br> 2. a .gitignore file for IntelliJ Java projects has been implemented <br> 3. There is not any redundant or copy/paste code in the JSPs or classes<br> 4. Classes are appropriately-sized (no monster classes)<br> Property files are used appropriately: no hard-coded values <br> 5. Logging statements are used rather than System.out.println and printStackTrace.<br> 6. There are appropriate unit tests/code coverage.  7. No sensitive information is visible in the repository (secrets, passwords, etc).|The project has a .gitignore file, and I did not identify any redundant code. There was not too much built out in this space, but everything was described appropriately. Carlos described the plan for logging, and outlined a unit test plan.  I did identify some secrets in the hibernate file within the repo.|

I also want to highlight how well Carlos was able to provide feedback through my lack of preparation. For what I had, he still had very constructive feedback and the project will be a greater success through the advise that he had given me.  Again I am very sorry for the delay Carlos, but I hope your project moves forward to success.

**Comment by pawaitemadisoncollege** [comment]
Hi @jhaefner97 - thanks for your review of @Carlos-Leon98's project so far. You did a good job balancing kudos with opportunities for improvement. 

One area for improvement when completing peer reviews is to provide some concrete, actionable suggestions. For example "industry lingo was hard to understand" - it might be helpful to identify some of the specific words/language that could be clarified to help @Carlos-Leon98 focus on the "right" areas.
